
<div class="contentLeft"><img src="/images/pageDescriptionImages/whitepaper.png" class="contentDescriptionImage"></div>
<div class="contentRight"><a id="new" href="#whitepaper_editor"><img src="/img/icons/page_white_add.png" />&nbsp;&nbsp;Whitepaper hinzuf&uuml;gen</a></div>
<div class="clearer"></div>

<div class="liste" id="liste">
    <?php echo $this->partial ('entriesPerPage.phtml', 'default'); ?>
    <table class="tableListe">
        <tr id="paginator" class="paginator">
            <td colspan="4" align="center">
                <?php echo $this->partial ('paginator.phtml', 'default'); ?>
            </td>
        </tr>
        <tr class="tableListeZeileHeader">
            <td>Kategorien</td>
            <td>Beschreibung</td>
            <td class="tableListeAction">Aktionen</td>
        </tr>
        <tr name="tableListeZeile" id="null" class="tableListeZeile" style="display:none">
            <td id="kategorien"></td>
            <td id="beschreibung"></td>
            <td><a id="edit" href="#whitepaper_editor"><img src="/img/icons/page_white_edit.png">&nbsp;&nbsp;Bearbeiten</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a id="del" href="#whitepaper_editor"><img src="/img/icons/page_white_delete.png">&nbsp;&nbsp;L&ouml;schen</a></td>
            <td class="hinweis" style="display:none"><img src="/images/icon_ausrufezeichen_klein.png" title="Dieser Eintrag muss zunächst durch unsere Redaktion geprüft werden. Wir bitten um etwas Geduld."></td>
        </tr>
        <tr id="paginator" class="paginator">
            <td colspan="4" align="center">
                <?php echo $this->partial ('paginator.phtml', 'default'); ?>
            </td>
        </tr>
    </table>
</div>

<!-- lightbox Edit-Fenster -->
<div style="display:none;">
    <div id="whitepaper_editor">
        <input type="HIDDEN" id="ID" value="">
        <table style="width:100%;">
            <tr><td class="formLightboxText">Kategorien:</td><td><input type="text" class="inputText inputTextLightbox"id="we_kategorien"name="whitepaper_kategorie"></td></tr>
            <tr><td class="formLightboxText">Beschreibung:</td><td>  <textarea class="textareaLightbox" id="we_beschreibung" name="whitepaper_beschreibung" cols=70 rows=4></textarea></td></tr>
            <tr><td class="formLightboxText">Link:</td><td> <input type="text" class="inputText inputTextLightbox"id="we_link" name="whitepaper_link"></td></tr>
            <tr><td class="formLightboxText">PDF-Datei:</td><td id="pdf"></td></tr>
        </table>

        <input id="buttonSave" class="buttonSave" type="button" value="  speichern"> 
    </div>
</div>
