<!-- BENUTZER - KOPF //-->

<div class="contentLeft"><img src="/images/pageDescriptionImages/accounts.png" class="contentDescriptionImage"></div>
<div class="clearer"></div>

<div class="left">
  <div class="contentRight" style="">
    <a href="#" onclick="call_action_fancy ('/admin/accounts/new', 400, 200);">
      <img src="/img/icons/page_add.png" style="margin-right: 5px;"/>Benutzer hinzufügen</a>    
  </div>   
</div>

<div class="right">
  <?= $this->search_form ?>
</div>  
 
<div class="clearer"></div>
<br>

<!-- BENUTZER LISTE //-->
<?php if (!empty ($this->userlist_paging)) : ?>
<table class="tableListe">    
    <tr>
      <td colspan="6" align="center">
        <?= $this->userlist_paging; ?>
      </td>
    </tr>
            
    <tr class="tableListeZeileHeader">
      <td>ID</td>
      <td>Username</td>
      <td>Anbieter</td>
      <td width="40">Status</td>
      <td>letzter Login</td>
      <td class="tableListeAction">Aktionen</td>
    </tr>
    
    <?php foreach ($this->userlist_paging as $user) : ?>    
      <tr class="tableData">
        <td><?= $user ['userID']; ?></td>
        <td><?= $user ['username']; ?></td>
        <td><?= $user ['firmenname']; ?></td>
        <td><?= $user ['userStatus']; ?></td>
        <td><?= $user ['last_login']; ?></td>
        <td>
          <a href="#" style="margin-right:20px;" onclick="call_action_fancy ('/admin/accounts/edit/user_id/<?= $user ['userID'] ?>', 400, 220);"><img src="/img/icons/page_edit.png"> Bearbeiten</a>
          <a href="#" onclick="call_action ('/admin/accounts/delete/user_id/<?= $user ['userID'] ?>');"><img src="/img/icons/page_delete.png"> Löschen</a>
        </td>
      </tr>
    <?php endforeach; ?>
            
    <tr>
      <td colspan="6" align="center">
        <?= $this->userlist_paging; ?>
      </td>
    </tr>    
  </table>
<?php endif; ?>

</div>