<?php

// das View bzw. Form wird "per Hand" gebaut, damit evtl. auch mal
// nicht-Programmierer dort etwas aendern koennen.

?>


<div id="user_liste" class="user_liste" >
  <div id="suchbegriff_div" class="suchbegriff_div"><input type="text" id="suchbegriff"></div>
  <div class="clearer"></div>
  <div id="tableHead" class="user_listeTabelleHeader">
    <div id="th_0" class="user_status">Status</div>
    <div id="th_1" class="user_listeTitleName">Username</div>
    <div id="th_2" class="user_listeTitleVorname">Vorname</div>
    <div id="th_3" class="user_listeTitleNachname">Nachname</div>
    <div id="th_4" class="user_listeTitleStrasse">Strasse</div>
    <div id="th_5" class="user_listeTitlePLZ">PLZ</div>
    <div id="th_6" class="user_listeTitleOrt">Ort</div>
  </div>
  <div id="tableBody" style="position:relative"></div>
  <div id="loader"></div>
  <div class="clearer"></div>
  <div id="pagination" class="paginationListe"></div>
   <div class="clearer"></div>
</div>
  <div id="userEditDialog" style="display:none">
     <input type="HIDDEN" id="userID" value="">
     <input type="HIDDEN" id="userDetailID" value="">
     <input type="HIDDEN" id="userHash" value="">
    <div id="linke_spalte" class="linkeSpaltePosition">
<!-- linke Spalte -->
      <div id="label_firma" class="benutzerPopupLabelText">
      Firma
      </div>
      <div id="input_firma" class="benutzerPopupAbstandtInput">
        <input type="text" name="firmenname" id="i_firma" class="benutzerPopupinputAusgabe">
        <div id="firmenname_status" class="benutzerPopupStatus"></div>
      </div>
      <div id="label_anrede" class="benutzerPopupLabelText">
      Anrede
      </div>
      <div id="input_anrede" class="benutzerPopupAbstandtInput">
        <select name="anredeID" id="i_anrede" class="benutzerPopupinputAusgabeSelekt">
          <?php
            foreach ($this->anreden as $anredeArray)
            {
          ?>
          <option value="<?php echo $anredeArray ['anredeID'];?>">
             <?php echo $anredeArray ['anrede']; ?>
          </option>
          <?php
            }
          ?>
        </select>
        <div id="anredeID_status" class="benutzerPopupStatus"></div>
      </div>
      <div id="label_vorname" class="benutzerPopupLabelText">
      Vorname
      </div>
      <div id="input_vorname" class="benutzerPopupAbstandtInput">
        <input type="text" name="vorname" id="i_vorname" class="benutzerPopupinputAusgabe">
        <div id="vorname_status" class="benutzerPopupStatus"></div>
      </div>
      <div id="label_strasse" class="benutzerPopupLabelText">
      Strasse
      </div>
      <div id="input_strasse" class="benutzerPopupAbstandtInput">
        <input type="text" name="strasse" id="i_strasse" class="benutzerPopupinputAusgabe">
        <div id="strasse_status" class="benutzerPopupStatus"></div>
      </div>
      <div id="label_stadt" class="benutzerPopupLabelText">
      Stadt
      </div>
      <div id="input_stadt"class="benutzerPopupAbstandtInput">
        <input type="text" name="stadt" id="i_stadt" class="benutzerPopupinputAusgabe">
        <div id="stadt_status" class="benutzerPopupStatus"></div>
      </div>
      <div id="label_telefon" class="benutzerPopupLabelText">
      Telefon
      </div>
      <div id="input_telefon" class="benutzerPopupAbstandtInput">
        <input type="text" name="telefon" id="i_telefon" class="benutzerPopupinputAusgabe">
        <div id="telefon_status" class="benutzerPopupStatus"></div>
      </div>
      <div id="label_email" class="benutzerPopupLabelText">
      E-Mail
      </div>
      <div id="input_email" class="benutzerPopupAbstandtInput">
        <input type="text" name="email" id="i_email" class="benutzerPopupinputAusgabe">
        <div id="email_status" class="benutzerPopupStatus"></div>
      </div>
    </div>
<!-- rechte Spalte -->
    <div id="rechte_spalte" class="rechteSpaltePosition">
      <div id="label_job" class="benutzerPopupLabelText">
      Job
      </div>
      <div id="input_job" class="benutzerPopupAbstandtInput">
        <input type="text" name="job" id="i_job" class="benutzerPopupinputAusgabe">
        <div id="job_status" class="benutzerPopupStatus"></div>
      </div>
      <div id="label_titel" class="benutzerPopupLabelText">
      Titel
      </div>
      <div id="input_titel"class="benutzerPopupAbstandtInput">
        <input type="text" name="titelID" id="i_titel" class="benutzerPopupinputAusgabe">
        <div id="titel_status" class="benutzerPopupStatus"></div>
      </div>
      <div id="label_nachname" class="benutzerPopupLabelText">
      Nachname
      </div>

      <div id="input_nachname" class="benutzerPopupAbstandtInput">
        <input type="text" name="nachname" id="i_nachname" class="benutzerPopupinputAusgabe">
        <div id="nachname_status" class="benutzerPopupStatus"></div>
      </div>
      <div id="label_plz" class="benutzerPopupLabelText">
      Postleitzahl
      </div>
      <div id="input_plz" class="benutzerPopupAbstandtInput">
        <input type="text" name="plz" id="i_plz" class="benutzerPopupinputAusgabe">
        <div id="plz_status" class="benutzerPopupStatus"></div>
      </div>
      <div id="label_land" class="benutzerPopupLabelText">
      Land
      <div id="input_land"  class="benutzerPopupAbstandtInput">
        <select name="landID" id="i_land" class="benutzerPopupinputAusgabeSelekt">
          <?php
            foreach ($this->laender as $key => $laenderArray)
            {
          ?>
          <option value="<?php echo $this->laender [$key] ['laenderID'];?>">
             <?php echo utf8_encode ($this->laender [$key] ['langname']); ?>
          </option>
          <?php
            }
          ?>
        </select>
        <div id="landID_status" class="benutzerPopupStatus"></div>
      </div>
      <div id="label_telefax" class="benutzerPopupLabelText">
      Telefax
      </div>
      <div id="input_telefax" class="benutzerPopupAbstandtInput">
        <input type="text" name="telefax" id="i_telefax" class="benutzerPopupinputAusgabe">
        <div id="telefax_status" class="benutzerPopupStatus"></div>
      </div>
      <div id="label_webseite" class="benutzerPopupLabelText">
      Webseite
      </div>
      <div id="input_webseite" style="position:relative" class="benutzerPopupAbstandtInput">
        <input type="text" name="webseite" id="i_webseite" class="benutzerPopupinputAusgabe">
        <div id="webseite_status" class="benutzerPopupStatus"></div>
      </div>
    </div>
    <div id="UserLoginDatenEdit">
      <div id="label_username" class="benutzerPopupLabelText">
      Username
      </div>
      <div id="input_username" class="benutzerPopupAbstandtInput">
        <input type="text" name="username" id="i_username" class="benutzerPopupinputAusgabe">
        <div id="username_status" class="benutzerPopupStatus"></div>
      </div>
    </div>
</div>

