<div class="page-header" style="margin-top:10px;">
  <div class="fl" style="min-width:150px;margin-right:250px;">
    <div class="btn-group">
        <a class="btn" href="javascript:call_action_fancy ('/media/index/new/media_type/<?= $this->media_type ?>', 400, 400);">
          <i class="icon-plus"></i>  <?= ($this->media_type == 1) ? 'Bilder' : 'Videos' ?>
        </a>
    </div>      
  </div>  
  <div class="fl"><?= $this->partial ('search.phtml', 'default') ?></div>   
  <div class="fr"><?= $this->partial ('copy.phtml', 'default') ?></div>
  <div class="clear"></div>  
</div>
        
<?php $type_partial = ($this->media_type == 1) ? 'images.phtml' : 'videos.phtml' ?>
<?= $this->partial ($type_partial, array ('data_paging' => $this->data_paging, 'media_type' => $this->media_type)) ?>  