<div class="page-header">
  <div class="fl"> <h4>Anbieterübersicht</h4></div>
  <div class="fr">
    <!-- ANBIETERAUSWAHL //-->  
    <select onchange ="window.location.href = '<?= /*$this->url ($this->url_params, '', true);*/ '/einfuehrung/index/index' ?>' + '?sato=' + this.value">
      <?php foreach ($this->selections AS $hash => $name) : ?>
        <option value="<?= $hash ?>"> <?= $name ?></option>
      <?php endforeach; ?>
    </select>
  </div>
  <div class="clear"></div>
</div>
  
<!-- SUCHERGEBNISSE LISTE//-->
<?php if (!empty ($this->search_results_paging)) : ?>  
  <table class="table table-hover">
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Strasse</th>
      <th>Plz</th>
      <th>Ort</th>    
      <th style="text-align:center;">Aktion</th>
    </tr>      
    <?php foreach ($this->search_results_paging as $search_result_row) : ?>
      <tr>
        <td><?= $search_result_row ['anbieterID'] ?></td>
        <td><?= $search_result_row ['firmenname'] ?></td>
        <td><?= $search_result_row ['strasse'] ?> <?= $search_result_row ['hausnummer'] ?></td>
        <td><?= $search_result_row ['plz'] ?></td>
        <td><?= $search_result_row ['ort'] ?></td>
        <td style="text-align:center;">          
          <a class="btn btn-small" title="Anbieter auswählen" href="<?= /*$this->url ($this->url_params, '', true)*/'/einfuehrung/index/index'.'?sato='.$search_result_row ['anbieterhash']; ?>">
            <i class="icon-user"></i>
          </a>          
        </td>
      </tr>
    <?php endforeach; ?>
                  
  <tr><td colspan="6" align="center" class="pr"><?= $this->search_results_paging ?></td></tr>        
  </table>

<?php else : ?>
<div class="alert alert-info" style="text-align:center;">Keine Suchergebnisse</div>  
<?php endif; ?>