<div class="page-header" style="margin-top:10px;">
   <button type="button" class="btn" onclick="check_form ();">Stammdaten speichern</button>            
</div>  

<form enctype="multipart/form-data" class="form-horizontal" action="/stammdaten/index/edit" name="form_address" method="POST">
  
  <div class="control-group">
    <label class="control-label">Firmenname*</label>
    <div class="controls">
      <input type="text" class="input-xxlarge" style="width:437px;" name="name1" value="<?= $this->data ['name1'] ?>">
    </div>
  </div>
  
  <div class="control-group">
    <label class="control-label"></label>
    <div class="controls">
      <input type="text" class="input-xxlarge" style="width:437px;" name="name2" value="<?= $this->data ['name2'] ?>">
    </div>
  </div>
  
  
  <div class="control-group">
    <label class="control-label">Straße, Hnr*</label>
    <div class="controls controls-row">
      <input type="text" class="input-xlarge" style="width:330px;" name="strasse" value="<?= $this->data ['strasse'] ?>">
      <input type="text" class="input-small" name="hausnummer" value="<?= $this->data ['hausnummer'] ?>">
    </div>
  </div>
  
  <div class="control-group">
    <label class="control-label">Plz, Ort*</label>
    <div class="controls">
      <input type="text" class="input-small" name="plz" value="<?= $this->data ['plz'] ?>">
      <input type="text" class="input-xlarge" style="width:330px;" name="ort" value="<?= $this->data ['ort'] ?>">
    </div>
  </div>
  
  <div class="control-group">
    <label class="control-label" for="fon">Telefon, Fax*</label>
    <div class="controls">
      <input type="text" class="input-large" name="fon" value="<?= $this->data ['fon'] ?>">
      <input type="text" class="input-large" name="fax" value="<?= $this->data ['fax'] ?>">
    </div>
  </div>
  
  <div class="control-group">
    <label class="control-label" for="email">Email, WWW*</label>
    <div class="controls">
      <input type="text" class="input-large" name="email" value="<?= $this->data ['email'] ?>">
      <input type="text" class="input-large" name="www" value="<?= $this->data ['www'] ?>">
    </div>
  </div>
      
  <div class="control-group">
    <label class="control-label" for="logo">Logo</label>
    <div class="controls">
      <input type="file" name="logo">
      <?php if ($this->logo) : ?>
        <img src="<?= $this->logo ?>" width="100" title="Firmenlogo"/>
      <?php endif; ?>
    </div>
  </div>
        
  <input type="hidden" name="stammdatenID" value="<?= $this->data ['stammdatenID'] ?>">
  <input type="hidden" name ="anbieterID" value="<?= $this->data ['anbieterID'] ?>">
</form>