<div class="contentLeft">
  <img src="/images/pageDescriptionImages/anbieter.png" class="contentDescriptionImage">
</div>
<div class="clearer"></div>

<div class="left">
  <div class="contentRight">
    <a href="#" onclick="call_action_fancy ('/admin/Anbieter/new', 350, 650);"><img src="/img/icons/user_add.png"/>Anbieter hinzufügen</a>  
  </div>
</div>

<div class="right">
  <?= $this->search_form ?>
</div>  

<div class="clearer"></div>
<br>

  <table class="tableListe">

    <tr>
      <td colspan="6" align="center">
        <?= $this->provider_paging ;?>
      </td>
    </tr>

    <tr class="tableListeZeileHeader">
      <td>VM-Kundennummer</td>
      <td>Anbieter-ID</td>
      <td>Anbietername</td>
      <td>Ort</td>
      <td>Premium</td>
      <td class="tableListeAction">Aktionen</td>
    </tr>
    
    <?php foreach ($this->provider_paging as $provider) : ?>
      <tr class="tableData">
        <td><?= $provider ['anbieterID']; ?></td>
        <td><?= $provider ['companyID']; ?></td>
        <td><?= $provider ['firmenname']; ?></td>
        <td><?= $provider ['ort']; ?></td>
        <td><?= $provider ['premiumLevel']; ?></td>
        <td class="tableListeAction">
          <a href="#" style="margin-right:20px;" onclick="call_action_fancy ('/admin/Anbieter/edit/provider_id/<?= $provider ['anbieterID'] ?>', 350, 650);"><img src="/img/icons/user_edit.png">Bearbeiten</a>
          <a href="#" onclick="call_action ('/admin/Anbieter/delete/provider_id/<?= $provider ['anbieterID'] ?>');"><img src="/img/icons/user_delete.png">Löschen</a>
        </td>
      </tr>
    <?php endforeach; ?>
    
    <tr>
      <td colspan="6" align="center">
        <?= $this->provider_paging ;?>
      </td>
    </tr>
    
  </table>