<ul>
<?php

$sessionNamespace = new Zend_Session_Namespace ();

foreach ($this->container as $page)
{
  if ($page->show == 'true')    
  {    
    ($this->layout ()->_module == $page->_module) ? $activeClass = 'active' : $activeClass = 'inactive';
    $imageName = $page->_module.".png";
    if (!file_exists (getcwd ()."/images/".$imageName)) $imageName = "noImage.png";
    if ($page->_module != "admin" OR ($page->_module == "admin" AND $sessionNamespace->userData ['userStatus'] < 0))	
    {
      echo "<li class='$activeClass'><a href='/".$page->_module."/".$page->_controller."/".$page->_action."'>";
      echo $page->label;
      echo "</a></li>";
    } 
  }
}

?>
</ul>