<ul class="submenu">
<?php

$anbieterLimits = Plugin_Global::getAnbieterLimitsBySession ();

$container = $this->container;

$found = $container->findBy ('module', $this->layout ()->_module);

if (is_array ($found))
{
  foreach ($found as $page)
  {
    $module = $page->_module;
    $controller = $page->_controller;
    $action = $page->_action;

    if ($page->isActive ()) //logDebug ($module."/".$controller."/".$action, "");
    if ($anbieterLimits->{'canuse_'.$module} == 1)
    {
          ($this->layout ()->_controller == $controller) ? $activeClass = 'activeSUB' : $activeClass = 'inactive';
          $imageName = $page->_module.".png";
          if (!file_exists (getcwd ()."/images/".$imageName)) $imageName = "noImage.png";
          echo "<li class='$activeClass'><a href='/".$page->_module."/".$page->_controller."/".$page->_action."'>";
          /*if ($page->showimage == 'true')
          {
              echo "<div class='menuImage'><img src='/images/".$imageName."'></div>";
          } else
              {
                  echo "<div class='menuImage'>&nbsp;</div>";
              }*/
          echo $page->label;
          echo "</a></li>";
    }
  }
}

?>
</ul>