<ul class="submenu">
<?php

$anbieterLimits = Plugin_Global::getAnbieterLimitsBySession ();
$container = $this->container;
$found = $container->findBy ('module', $this->layout ()->_module);

if (!empty ($found))
{
  foreach ($found as $page)
  {      
    if ($anbieterLimits->{'canuse_'.$page->_module} == 1)
    {
          ($this->layout ()->_controller == $page->_controller) ? $activeClass = 'activeSUB' : $activeClass = 'inactive';
          $imageName = $page->_module.".png";
          if (!file_exists (getcwd ()."/images/".$imageName)) $imageName = "noImage.png";
          echo "<li class='$activeClass'><a href='/".$page->_module."/".$page->_controller."/".$page->_action."'>";          
          echo $page->label;
          echo "</a></li>";
    }
  }
}

?>
</ul>