<div class="page-header" style="margin-top:10px;">
  <div class="fl" style="min-width:150px;margin-right:250px;">
    <div class="btn-group">
        <a class="btn" href="javascript:call_action_fancy ('/termine/index/new', 400, 600);">
          <i class="icon-plus"></i>  Termine
        </a>
    </div>      
  </div>  
  <div class="fl"><?= $this->partial ('search.phtml', 'default') ?></div>   
  <div class="fr"><?= $this->partial ('copy.phtml', 'default') ?></div>
  <div class="clear"></div>  
</div>

    
<table class="table table-hover">
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>              
      <th>Beginn</th>
      <th>Ende</th>
      <th>Ort</th>
      <th>Typ</th>
      <th class="ar">Aktionen</th>
    </tr>
  </thead>
  <tbody>
    <?php if (!empty ($this->data_paging)) : ?>
      <?php foreach ($this->data_paging as $search_result_row) : ?>
        <tr>
          <td><?= $search_result_row ['id'] ?></td>
          <td><?= $search_result_row ['title'] ?></td>              
          <td><?= $search_result_row ['beginn'] ?></td>
          <td><?= $search_result_row ['ende'] ?></td>
          <td><?= $search_result_row ['ort'] ?></td>
          <td><?= $this->date_types [$search_result_row ['typID']] ?></td>
          <td style="text-align: center;">
            <div class="btn-group">
              <a class="btn" title="Bearbeiten" href="javascript:call_action_fancy ('/termine/index/edit/id/<?= $search_result_row ['id'] ?>', 400, 600);">
                <i class="icon-pencil"></i>
              </a>
              <a class="btn" title="Löschen" href="javascript:call_action ('/termine/index/delete/id/<?= $search_result_row ['id'] ?>', true)">
                <i class="icon-trash"></i>
              </a>
              <?php if (!empty ($search_result_row ['media'])) : ?>
                <a class="btn" title="Bild" onclick="show_preview ('<?= $search_result_row ['media'] ?>');"><i class="icon-eye-open"></i></a>
              <?php else : ?>
                <a class="btn disabled" title="Bild"><i class="icon-eye-close"></i></a>
              <?php endif; ?>              
            </div>
          </td>
        </tr>
      <?php endforeach; ?>                     
      <tr>
        <td colspan="7" align="center" class="pr">
          <?= $this->data_paging ?>
        </td>
      </tr>
      <?php else : ?>
      <tr class="warning">
        <td colspan="7" style="text-align:center;"><b>Keine Einträge vorhanden!</b></td>
      </tr>  
    <?php endif; ?>   
  </tbody>
</table>