<div class="page-header">  
  <div class="fl">
    <h4>Willkommen zum WEKA FACHMEDIEN Anbieterverzeichnis!</h4>
  </div>  
  <div class="fr">
    <?= $this->partial ('preview.phtml') ?>
  </div>  
  <div class="clear"></div>
</div>
         
<table class="table nmb">
  <thead>
    <tr>       
      <th style="width:200px;">Medienmarke</th>
      <th style="width:200px;">Status</th>
      <th style="width:200px;">Beginn</th>
      <th style="width:200px;">Ende</th>
      <th style="width:200px;">Laufzeit</th>            
    </tr>  
  </thead>
  <tbody>    
    <?php foreach ($this->overview as $system_id => $row) : ?>
      <tr>                 
        <td style="vertical-align:middle;"><img src="/brands/<?= $row ['system'] ?>.png" title="<?= $row ['system'] ?>"/></td>
        <td style="vertical-align:middle;">          
          <?php if ($this->user_status == -1) : ?>
            <?php $ident = sha1 ($row ['system']); ?>
            <?= $this->partial ('status_dropdown.phtml', array ('system' => $row ['system'], 'system_id' => $system_id, 'premium' => $row ['premium'], 'ident' => $ident)) ?>          
          <?php else : ?> 
            <?= ($row ['premium'] == 0) ? 'Standard' : 'Premium' ?>        
          <?php endif; ?>
        </td>            
        <td style="vertical-align:middle;"><?= (!empty ($row ['start'])) ? $row ['start'] : '-' ?></td>            
        <td style="vertical-align:middle;"><?= (!empty ($row ['end'])) ? $row ['end'] : '-'  ?></td>            
        <td style="vertical-align:middle;"><?= (!empty ($row ['laufzeit'])) ? $row ['laufzeit'] : '-' ?></td>                
      </tr>
      <?php if ($this->user_status == -1) : ?>       
        <tr id="<?= $ident ?>" class="info" style="display:none;">          
          <td colspan="5" style="vertical-align:middle;">                        
            <?php $action = ($row ['premium'] == 1) ? 'premiumedit' : 'premium' ?>
            <?php $start = (!empty ($row ['start'])) ? $row ['start'] : date ('d.m.Y') ?>
            <?php $end = (!empty ($row ['end'])) ? $row ['end'] : date ('d.m.Y', mktime (0, 0, 0, date ('m'), date ('d'), date ('y') + 1)) ?>                        
            <?= $this->partial ('status_form.phtml', array ('ident' => $ident, 'system_id' => $system_id, 'action' => $action, 'start' => $start, 'end' => $end)) ?>                                    
          </td>                                    
        </tr>  
      
      <?php endif; ?>
      
     <?php endforeach; ?> 
   </tbody>      
</table>     