
<input type="HIDDEN" id="premiumLevel" value="<?php echo $this->premiumLevel; ?>">

<img src="/images/pageDescriptionImages/accountdetails.png" class="contentDescriptionImage">

<!-- ANBIETER-ACCOUNT-INFO //-->
<table border="0" style="width:100%;"> 
    <tr>
        <td style="width:30%;">Anbieter:</td>
        <td style="width:70%;">            
              <div class="inputText accountDetailsInput"><?= $this->name; ?></div>            
        </td>
    </tr> 
    <tr>
        <td>Letzter Login:</td>
        <td>
            <div class="inputText accountDetailsInput"><?= $this->lastLogin; ?></div>
        </td>
    </tr>                        
    <tr>
        <td>Status:</td>
        <td>
            <?php if ($this->userstatus < 0) : ?>
              <a href="#" id="accountStatusSwitcherUE">
            <?php else : ?>
              <a href="#changeData" class="changeDataLightbox">
            <?php endif; ?>                
              <div class="inputText accountDetailsInput"><img id="accountStatusImageUE" />&nbsp;&nbsp;<span id="accountStatusTextUE"></span></div>
            </a>
        </td>
    </tr> 
    <tr>
        <td>Beginn:</td>
        <td>            
              <div class="inputText accountDetailsInput"><?= $this->startdatum; ?></div>            
        </td>
    </tr> 
    <tr>
        <td>Ablauf:</td>
        <td>            
          <div class="inputText accountDetailsInput"><?= $this->enddatum; ?></div>            
        </td>
    </tr> 
    <tr>
        <td>Restlaufzeit:</td>
        <td>            
          <div class="inputText accountDetailsInput"><?= $this->restlaufzeit; ?> Tage</div>            
        </td>
    </tr> 
</table>

<!-- POPUP NON-ADMIN //-->
<div style="display:none;">
    <div id="changeData" style="text-align:center;">
        <h1>M&ouml;chten Sie Ihre Daten &auml;ndern?</h1>
        Um essentielle Daten Ihres Accounts &auml;ndern zu k&ouml;nnen, m&uuml;ssen Sie uns kontaktieren. Am einfachsten geht dies per E-Mail an Frau Lydia Sattelberger (<a href="mailto:lsattelberger@elektroniknet.de">lsattelberger@elektroniknet.de</a>) oder Telefon unter 089/25556-1303</div>
</div>
