<div class="page-header" style="margin-top:10px;">
  <div class="fl" style="min-width:150px;margin-right:250px;">
    <div class="btn-group">
        <a class="btn" href="javascript:call_action_fancy ('/ansprechpartner/index/new', 375, 450);">
          <i class="icon-plus"></i>  Ansprechpartner
        </a>
    </div>      
  </div>  
  <div class="fl"><?= $this->partial ('search.phtml', 'default') ?></div>   
  <div class="fr"><?= $this->partial ('copy.phtml', 'default') ?></div>
  <div class="clear"></div>  
</div>

  <table class="table table-hover">    
    <thead>
    <tr>
      <th>ID</th>
      <th>Vorname</th>
      <th>Nachname</th>
      <th>Telefon</th>
      <th>Email</th>      
      <th class="ar">Aktionen</th>
    </tr>
    </thead>         
          
     <?php if (!empty ($this->data_paging)) : ?>
      <tbody>
        <?php foreach ($this->data_paging as $search_result_row) : ?>
          <tr>
            <td><?= $search_result_row ['id'] ?></td>
            <td><?= $search_result_row ['vorname'] ?></td>
            <td><?= $search_result_row ['nachname'] ?></td>
            <td><?= $search_result_row ['telefon'] ?></td>
            <td><?= $search_result_row ['email'] ?></td>                        
            <td style="text-align:center;">
              <div class="btn-group">                
                <a class="btn" title="Bearbeiten" href="javascript:call_action_fancy ('/ansprechpartner/index/edit/id/<?= $search_result_row ['id'] ?>', 375, 450);">  
                  <i class="icon-pencil"></i>
                </a>              
                <a class="btn" title="Löschen" href="javascript:call_action ('/ansprechpartner/index/delete/id/<?= $search_result_row ['id'] ?>', true);">
                  <i class="icon-trash"></i>
                </a>              
              </div>              
            </td>
          </tr>
        <?php endforeach; ?>            
        <tr>
          <td colspan="7" align="center" class="pr">
            <?= $this->data_paging ?>
          </td>
        </tr>
        <?php else : ?>
          <tr class="warning">
            <td colspan="7" style="text-align:center;"><b>Keine Einträge vorhanden!</b></td>
          </tr>  
        <?php endif; ?>    
      </tbody>
  </table>

