<div class="contextMenu" id="myMenu1" style="visibility:hidden">
  <ul>
    <li id="edit"><img src="/img/edit.png" />Paket bearbeiten</li>
    <li id="del"><img src="/img/cancel.png" />Paket l&ouml;schen</li>
    <hr>
    <li id="lock"><img src="/img/delete.png" />Paket sperren</li>
    <li id="unlock"><img src="/img/tick.png" />Paket freigeben</li>
    <hr>
    <li id="new"><img src="/img/new.png">neues Paket anlegen</li>
  </ul>
</div>

