<div class="contextMenu" id="myMenu1" style="visibility:hidden">
  <ul>
    <li id="edit"><img src="/img/edit.png" />Produkt bearbeiten</li>
    <li id="del"><img src="/img/cancel.png" />Produkt l&ouml;schen</li>
    <hr>
    <li id="lockproduct"><img src="/img/delete.png" />Produkt sperren</li>
    <li id="unlock"><img src="/img/tick.png" />Produkt freigeben</li>
    <hr>
    <li id="new"><img src="/img/new.png">neues Produkt anlegen</li>
  </ul>
</div>

