<div class="contextMenu" id="myMenu1" style="visibility:hidden">
  <ul>
    <li id="edit"><img src="/img/edit.png" />Benutzer bearbeiten</li>
    <li id="del"><img src="/img/cancel.png" />Benutzer l&ouml;schen</li>
    <hr>
    <li id="lockuser"><img src="/img/delete.png" />Benutzer sperren</li>
    <li id="unlock"><img src="/img/tick.png" />Benutzer freigeben</li>
    <hr>
    <li id="new"><img src="/img/new.png">neuen Benutzer anlegen</li>
  </ul>
</div>

