<div class="left"> 
	
<table class="edit_table"> 
	
<input type="hidden" name="id" value="" helper="formHidden" id="ID" /> 
<input type="hidden" name="anbieterHash" value="<?php echo $this->anbieterHash; ?>" helper="formHidden" id="anbieterHash" /> 
<input type="hidden" name="anbieterID" value="<?php echo $this->anbieterID; ?>" helper="formHidden" id="anbieterID" /> 
<tr class="formRow"><td class="elementLabel"><label for="products">Produkte / Linecard:</label></td><td class="element"><textarea name="products" id="produkte" helper="formTextarea" rows="24" cols="80"></textarea><div class="suggestBox" id="suggestBoxProducts"></div></td></tr> 
<tr class="formRow"><td class="elementLabel"><label for="focus">Firmenausrichtung:</label></td><td class="element"><textarea name="focus" id="firmenausrichtung" helper="formTextarea" rows="24" cols="80"></textarea><div class="suggestBox" id="suggestBoxFocus"></div></td></tr> 
<tr class="formRow"><td class="elementLabel"><label for="service">Dienstleistungen:</label></td><td class="element"><textarea name="service" id="dienstleistungen" helper="formTextarea" rows="24" cols="80"></textarea><div class="suggestBox" id="suggestBoxService"></div></td></tr> 
<tr class="formRow"><td class="elementLabel"><label for="presence">Präsenz:</label></td><td class="element"><textarea name="presence" id="praesenz" helper="formTextarea" rows="24" cols="80"></textarea><div class="suggestBox" id="suggestBoxPresence"></div></td></tr> 
<tr class="formRow"><td class="elementLabel"><label for="markets">Zielmärkte:</label></td><td class="element"><textarea name="markets" id="zielmaerkte" helper="formTextarea" rows="24" cols="80"></textarea><div class="suggestBox" id="suggestBoxMarkets"></div></td></tr>	</table><br /> 
	<input type="submit" name="save" id="save" value="Speichern" helper="formSubmit" /> 
</div> 
<div class="left" style="padding-left: 25px;"> 
	<table class="edit_table"> 
	
<tr class="formRow"><td class="elementLabel"><label for="locations">Standorte / Lager:</label></td><td class="element"><textarea name="locations" id="standorte" helper="formTextarea" rows="24" cols="80"></textarea><div class="suggestBox" id="suggestBoxLocations"></div></td></tr> 
<tr class="formRow"><td class="elementLabel"><label for="quality">Qualitätsmanagement:</label></td><td class="element"><textarea name="quality" id="qualitaetsmanagement" helper="formTextarea" rows="24" cols="80"></textarea><div class="suggestBox" id="suggestBoxQuality"></div></td></tr> 
<tr class="formRow"><td class="elementLabel"><label for="founded">Gründungsjahr:</label></td><td class="element"><textarea name="founded" id="gruendungsjahr" helper="formTextarea" rows="24" cols="80"></textarea><div class="suggestBox" id="suggestBoxFounded"></div></td></tr> 
<tr class="formRow"><td class="elementLabel"><label for="staff">Mitarbeiter:</label></td><td class="element"><textarea name="staff" id="mitarbeiter" helper="formTextarea" rows="24" cols="80"></textarea><div class="suggestBox" id="suggestBoxStaff"></div></td></tr> 
<tr class="formRow"><td class="elementLabel"><label for="sales">Umsatz:</label></td><td class="element"><textarea name="sales" id="umsatz" helper="formTextarea" rows="24" cols="80"></textarea><div class="suggestBox" id="suggestBoxSales"></div></td></tr>	</table> 
</div> 
<div class="clearer"></div> 
</div> 
</div> 
