<table class="table table-hover">
  <thead>
  <tr>
    <th>ID</th>   
    <th>Beschreibung</th>
    <th>Code</th>
    <th class="ar">Aktionen</th>
  </tr>
  </thead>
  <?php if (!empty ($this->data_paging)) : ?>
  <tbody>
    <?php foreach ($this->data_paging as $search_result_row) : ?>
      <tr>
        <td><?= $search_result_row ['id'] ?></td>
         <td><?= $search_result_row ['beschreibung'] ?></td>
         <td><pre><?= htmlentities ($search_result_row ['media']) ?></pre></td>                
        <td style="text-align:center;">
          <div class="btn-group">
            <a class="btn" title="Bearbeiten" onclick="call_action_fancy ('/media/index/edit/id/<?= $search_result_row ['id'] ?>/media_type/<?= $this->media_type ?>', 400, 400);">
              <i class="icon-pencil"></i>
            </a>
            <a class="btn" title="Löschen" onclick="call_action ('/media/index/delete/id/<?= $search_result_row ['id'] ?>', true);">
              <i class="icon-trash"></i>
            </a>
            <?php if (!empty ($search_result_row ['media'])) : ?>
            <a class="btn" title="Video" onclick="show_preview ('<?= htmlentities ($search_result_row ['media']) ?>', true);"><i class="icon-eye-open"></i></a>
            <?php else : ?>
              <a class="btn disabled" title="Bild"><i class="icon-eye-close"></i></a>
            <?php endif; ?>
          </div>
        </td>
      </tr>      
    <?php endforeach; ?>           
    <tr>
      <td colspan="6" align="center" class="pr">
        <?= $this->data_paging ?>
      </td>
    </tr>
  <?php else : ?>
    <tr class="warning">
      <td colspan="6" style="text-align:center;"><b>Keine Einträge vorhanden!</b></td>
    </tr>  
    <?php endif; ?>   
  </tbody>
</table>