<?php
    
  //Jahreszahl fuer Footer
  $year = new Zend_Date ();
  $year = $year->get ('yyyy');

  //Browser erkennen
  $useragent = $_SERVER ['HTTP_USER_AGENT'];  
  $browser = '';
  if (preg_match ('|MSIE ([0-9].[0-9]{1,2})|', $useragent, $matched))
  {
    $browser = 'IE';
    $browser_version = $matched [1];
    $browserVersionArr = explode ('.', $browser_version);
    if ($browserVersionArr [0] <= '7')
    {
      echo $this->render ('noIE.html');
      die ();
    }
  }
  
  //Anbieter- und User-Daten aus Session holen - werden beim Login gesetzt
  $session = new Zend_Session_Namespace ();
  $this->anbieter = $session->anbieterData;
  $this->userData = $session->userData;
               
  //Hash des eigenen Anbieters holen - fuer Zurueck Knopf (Admin)
  $model = new Model_DbTable_AnbieterData (array ('provider_id' => $this->userData ['anbieterID']));
  $user_anbieterdata = $model->getAnbieter ();
  $user_anbieterhash = $user_anbieterdata ['anbieterhash'];
      
  //aktuelle (s) Modul, Controller und Action holen
  $usedModule = $this->layout ()->_module;
  $usedController = $this->layout ()->_controller;
  $usedAction = $this->layout ()->_action;  
  
  $request = Zend_Controller_Front::getInstance()->getRequest()->getParams();  
  
  //Anbieter-Suche
  $search_form = new Form_Search ();
  $search_term = $search_form->getElement ('search_term');  
  $search_term->setAttrib ('placeholder', 'Anbietersuche');   
  if ($usedModule == 'admin')
    $search_form->populate ($request);      
?>

<!-- Head //-->

<!DOCTYPE html>
<html style="height:102%;">
<head>
  <?php  
  echo $this->headTitle ('WCOS2');
  echo $this->headScript ()      
  ->prependFile ('/js/jquery/jquery-1.9.1.min.js')                             
  ->appendFile ('/js/fancybox/jquery.fancybox.pack.js')             
  ->appendFile ('/js/tinymce4/tinymce.min.js')   
  ->appendFile ('/twitter_bootstrap/js/bootstrap.min.js')             
  ->appendFile ('/js/jquery/jquery-ui.js')
  ->appendFile ('/js/jquery/jquery.ui.datepicker.js')             
  ->appendFile ('/js/main.js');
  echo $this->headLink ()
  ->appendStylesheet ('/css/style.css')
  ->appendStylesheet ('/js/fancybox/jquery.fancybox.css')      
  ->appendStylesheet ('/css/jquery/jquery-ui-1.8.2.custom.css')
  ->appendStylesheet ('/twitter_bootstrap/css/bootstrap.css');
  
  if ($browser == 'IE')
  {
    $browserVersionArr = explode ('.', $browser_version);
    if ($browserVersionArr [0] <= '8')    
      echo ('<link rel="stylesheet" type="text/css" media="screen" href="/css/IEfix.css">');    
  }
  ?>

</head>
<body>
<div class="wrapper">
  <div class="header">
       
    <!-- Contact -->
    <div id="contact" class="info contact_info">            
      <div class="fl"><a href="http://www.weka-fachmedien.de" target="_blank"><img src="/images/weka_logo.gif" title="WEKA Fachmedien"/></a></div>
      <div class="fl">
        <b>Sie haben Fragen zum Anbieterverzeichnis?</b><br> 
        Dann können Sie uns unter per Email an <a href="mailto:technik@weka-fachmedien.de" target="_blank">technik@weka-fachmedien.de</a><br>
        erreichen oder telefonisch unter der Nummer: +49 (0)89.255 56-1000<br>
      </div>
      <div class="fl"><a href="mailto:technik@weka-fachmedien.de?subject='WCOS Premium-Account'" target="_blank"><img src="/images/premium.png" /></a></div>
      <div class="fl"><b>Werden Sie jetzt <a href="mailto:technik@weka-fachmedien.de?subject='WCOS Premium-Account'" target="_blank">Premium-Anbieter!</a></b><br>Präsentieren Sie Ihr Unternehmen<br>im vollen Umfang.</div>
      <div class="clear"></div>                      
    </div>  
    
    <!-- Infobar -->         
    <div class="info">     
      <div class="navbar">
        <div class="navbar-inner infobar" style="border-top-right-radius:0px;border-top-left-radius:0px;">
          <ul class="nav">
            <a class="brand" href="#" style="font-size:14px;" title="Kd.nr.: <?= $this->anbieter ['anbieterID'] ?>"><img src="/images/buttonGreen.png" class="status_img"/><?php echo $this->anbieter ['firmenname']; ?></a>                                  
          </ul>          
                    
          <ul class="nav pull-right">
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#">Aktionen<b class="caret"></b></a>              
              <ul class="dropdown-menu">
                <li><a href="" onclick="$('#contact').slideToggle();return false;">Info</a></li>
                <li class="divider"></li>
                <?php if ($this->userData ['anbieterID'] != $this->anbieter ['anbieterID']) : ?>                    
                  <li><a href="<?=  '/'.$usedModule.'/'.$usedController.'/'.$usedAction.'/sato/'.$user_anbieterhash ?>">eigener Anbieter</a></li>           
                <?php endif; ?>
                <li><a href="/login/index/logout">Logout</a></li>  
              </ul>
            </li>
          </ul>
          <?php if ($this->userData ['userStatus'] == -1) : ?>
            <ul class="nav pull-right" style="margin-top:5px;"><?= $search_form ?></ul>
          <?php endif; ?>
        </div>
      </div>               
    </div>
  <div class="clearer"></div>
  
<div class="wrapper">  
    
  <div class="fl">
    <h2 style="margin:0px;line-height:20px;"><small>W.C.O.S. Anbieterverzeichnis</small></h2>
  </div>
  <div class="fr">
    <h2 style="margin:0px;line-height:20px;float:left;margin-right:20px;"><small>Sitzung für Medienmarke</small></h2>
          <span style="float:right;"><?= $this->partial ('systems.phtml', 'default') ?></span>
          <span class="clear"></span>
  </div>
  <div class="clear"></div>
  
  <!-- Menu -->
  <div class="navbar" style="margin-top:20px;">
    <div class="navbar-inner">  
      <?php
      if (!empty ($this->userData))
      {
        // Ausgabe der Main-Navigation
        $partial = array('menu.phtml', 'default');
        $this->navigation ()->menu ()->setPartial ($partial);
        echo $this->navigation ()->menu ()->setMinDepth (0)->setMaxDepth (0);        
      }
      ?>
    </div>  
  </div>
</div>

<div class="clearer"></div>

  <!-- content -->                  
  <div class="content">
    <?php echo $this->layout ()->content; ?>
  </div>
  
  <!-- footer -->
  <div class="footer">
    Software-Version 2.1<br/>
    Copyright &copy; <?php echo $year; ?> WEKA Fachmedien GmbH. Alle Rechte vorbehalten.
  </div>
 
</body>