<?php
    
  //Jahreszahl fuer Footer
  $year = new Zend_Date ();
  $year = $year->get ('yyyy');

  //Browser erkennen
  $useragent = $_SERVER ['HTTP_USER_AGENT'];  
  $matched = array ();
  if (preg_match ('|MSIE ([0-9].[0-9]{1,2})|', $useragent, $matched))
  {
    $browser_version = $matched [1];
    $browser = 'IE';
  }
  elseif (preg_match ('|Opera/([0-9].[0-9]{1,2})|', $useragent, $matched))
  {
    $browser_version = $matched [1];
    $browser = 'Opera';
  }
  elseif (preg_match ('|Firefox/([0-9\.]+)|', $useragent, $matched))
  {
    $browser_version = $matched [1];
    $browser = 'Firefox';
  }
  elseif (preg_match ('|Safari/([0-9\.]+)|', $useragent, $matched))
  {
    $browser_version = $matched [1];
    $browser = 'Safari';
  } else
  {
    //Browser nicht erkannt!
    $browser_version = 0;
    $browser = 'anderer';
  }

  //IE abfangen
  logDebug (print_r ($browser, true), "layout usergent");
  if ($browser == 'IE')
  {
    $browserVersionArr = explode ('.', $browser_version);

    if ($browserVersionArr [0] <= '7')
    {
      echo $this->render ('noIE.html');
      die ();
    }
  }

  //Anbieter- und User-Daten aus Session holen - werden beim Login gesetzt
  $sessionNamespace = new Zend_Session_Namespace ();
  $this->anbieter = $sessionNamespace->anbieterData;
  $this->userData = $sessionNamespace->userData;
           
  //Hash des eigenen Anbieters holen - fuer Zurueck Knopf (Admin)
  $model = new Model_DbTable_AnbieterData ();
  $user_anbieterdata = $model->getAnbieterByKundennummer ($this->userData ['anbieterID']);
  $user_anbieterhash = $user_anbieterdata ['anbieterhash'];
  
  //aktuelle (s) Modul, Controller und Action holen
  $usedModule = $this->layout ()->_module;
  $usedController = $this->layout ()->_controller;
  $usedAction = $this->layout ()->_action;  
?>

<!-- Head //-->

<!DOCTYPE html>
<html>
<head>
  <?php
  //echo $this->headMeta ()->appendName ('keywords', $metaData);  
  echo $this->headTitle ('WEKA FACHMEDIEN Anbieterverzeichnis');
  echo $this->headScript ()
  ->prependFile ('/js/modernizr.js')
  ->prependFile ('/js/functions.js')
  ->prependFile ('/js/jquery/jquery.ajaxmanager.js')
  ->prependFile ('/js/jquery/jquery.delay.js')
  ->prependFile ('/js/jquery/jquery.json-2.2.min.js')
  ->prependFile ('/js/jquery/jquery-form.js')
  ->prependFile ('/js/jquery/jquery.base64.js')
  ->prependFile ('/js/jquery/jquery-1.4.2.js')  
  ->appendFile ('/js/jquery/jquery-ui-1.7.2.custom.min.js')
  //->appendFile ('/js/jquery.selectbox.js')
  ->appendFile ('/js/fancybox/jquery.fancybox-1.3.4.pack.js')
  ->appendFile ('/js/dialog.js')
  //->appendFile ('/js/contextmenu.js')
  //->appendFile ('/js/admin.' . $usedController . '.js')
  ->appendFile ('/js/general.js')
  //->appendFile ('/js/jquery.prettyPhoto.js')
  //->appendFile ('/js/admin.' . $usedController . '.js')
  ->appendFile ('/js/' . $usedModule . '.js')
  ->appendFile ('/js/paginator.inc.js')
  ->appendFile ('/js/statusbox.js')
  ->appendFile ('/js/jquery/jquery-ui-timepicker-addon-0.6.2.js')
  //->appendFile ('/js/controlcenter.js')
  //->appendFile ('/js/nicEdit.js')
  ->appendFile ('/js/tinymce/jscripts/tiny_mce/tiny_mce.js')
  ->appendFile ('/js/fileuploader.js')
  ->appendFile ('/js/accountDetails.js')
  ->appendFile ('/js/suche.js');
  echo $this->headLink ()
  ->appendStylesheet ('/css/style.css')
  ->appendStylesheet ('/js/fancybox/jquery.fancybox-1.3.4.css')
  //->appendStylesheet ('/js/jqGrid/css/ui.jqgrid.css')
  ->appendStylesheet ('/js/jquery/autocomplete/jquery.autocomplete.css')
  ->appendStylesheet ('/css/fileuploader.css')
  ->appendStylesheet ('/css/jquery/jquery-ui-1.8.2.custom.css');

  if ($browser == 'IE')
  {
    $browserVersionArr = explode ('.', $browser_version);
    if ($browserVersionArr [0] <= '8')
    {
      echo ('<link rel="stylesheet" type="text/css" media="screen" href="/css/IEfix.css">');
    }
  }
  ?>

</head>
<body>
<input type="hidden" name="module" id="module" value="<?= $usedModule; ?>">
<input type="hidden" name="controller" id="controller" value="<?= $usedController; ?>">
<input type="hidden" name="action" id="action" value="<?= $usedAction; ?>">
<input type="HIDDEN" id="anbieterID" value="<?= $this->anbieter ['anbieterID']; ?>">
<input type="HIDDEN" id="anbieterHash" value="<?= $this->anbieter ['anbieterhash']; ?>">
<input type="HIDDEN" id="premiumLevel" value="<?= $this->anbieter ['premiumLevel']; ?>">
<input type="HIDDEN" id="premiumHash" value="<?= $this->layout ()->premiumHash; ?>">
<input type="HIDDEN" id="uhx" value="<?= $this->userData ['userHash'] ?>">
<input type="HIDDEN" id="userStatus" value="<?= $this->userData ['userStatus']; ?>">
<input type="HIDDEN" id="host" value="<?= $_SERVER ['HTTP_HOST'] ?>">
<input type="HIDDEN" id="ajaxReturnData" value="">
<input type="HIDDEN" id="tempdata" value="">
<input type="HIDDEN" id="vmkdnrhx" value="<?= $this->userData ['anbieterID']; ?>">

<div class="bar"></div>
<div class="wrapper">

  <div class="header">
    <div class="logo"></div>
   
    <!-- Account Info -->
    <div class="accountInfo">      
      <div class="anbieter">Anbieter: <?php echo $this->anbieter ['firmenname']; ?></div>
      
      <div class="status">
      Account Status:&nbsp;&nbsp;<img id="accountStatusImage"/>&nbsp;&nbsp;<span
      id="accountStatusText"></span>
      <?php if ($this->userData ['anbieterID'] != $this->anbieter ['anbieterID']) : ?>
        <input type="button" value="zurück" onclick="window.location.href = '<?= '/'.$usedModule.'/'.$usedController.'/'.$usedAction.'/sato/'.$user_anbieterhash ?>'">
      <?php endif; ?>
      </div>                          	
    </div>
    <div class="clearer"></div>
  </div>
  <div class="clearer"></div>

  <!-- Menu -->
<div class="wrapper">
  <div class="menu">
  <?php
  if ($this->loginStatus () > 0)
  {
    // Ausgabe der Main-Navigation
    $partial = array('menu.phtml', 'default');
    $this->navigation ()->menu ()->setPartial ($partial);
    echo $this->navigation ()->menu ()->setMinDepth (0)->setMaxDepth (0);

    // Ausgabe der Sub-Navigation
    $partial = array('submenu.phtml', 'default');
    $this->navigation ()->menu ()->setPartial ($partial);
    $this->navigation ()->menu ()->setMinDepth (1);
    $this->navigation ()->menu ()->setRenderParents (false);
    $this->navigation ()->menu ()->setOnlyActiveBranch (true);
    echo $this->navigation ()->menu ()->renderPartial (); 
  }
  ?>
  </div>
</div>

<div class="clearer"></div>

  <!-- content -->                  
  <div class="content">
    <?php echo $this->layout ()->content; ?>
  </div>
  

  <div id="ja_nein_dialog" style="display:none" title="">
    <p id="jn_dialog_text"></p>
  </div>
  
  <!-- footer -->
  <div class="footer">Software-Version 2.1<br/>Copyright &copy; <?php echo $year; ?> WEKA
    Fachmedien GmbH. Alle Rechte vorbehalten.
  </div>
  <div class="preload"><img src="/images/button.png"><img src="/images/buttonHover.png"><img
  src="/images/buttonActive.png"><img src="/images/inputTextActive.png"><img src="/images/inputTextInactive.png"><img
  src="/images/InputActiveLightbox.png"><img src="/images/InputInactiveLightbox.png"><img
  src="/images/searchBox.png"><img src="/images/searchBoxFocus.png"></div>
</body>