<!-- Tags -->

<div id="statusBox" class="controlCenter">
  <div id="controlCenterNavigation" class="controlCenterNavigation">
   	<div class="controlCenterNavigationText">Tags</div>
   	<div class="controlCenterNavigationIcon"></div>
  </div>
  <div class="controlBoxText" id="weitereTags">weitere Tags zuordnen</div>
  <div id="tagDialog"></div>
  <div class="controlAbstand"></div>
</div>

