<?php

// das View bzw. Form wird "per Hand" gebaut, damit evtl. auch mal
// nicht-Programmierer dort etwas aendern koennen.

?>


<div id="productListe" class="produkte_liste">
  <div id="produkte_suchbegriff" class="produkte_suchbegriff">
    <input type="text" id="suchbegriff">
  </div>
   <div class="clearer"></div>
  <div id="tableHead" class="produkte_listeTabelleHeader">
    <div id="th_0" class="produkte_status">Status</div>
    <div id="th_1" class="produkte_listeNameTitle">Titel</div>
    <div id="th_2" class="produkte_TitleTeaserListe">Teaser</div>
    <div id="th_3" class="produkte_TitleTeaserListe">Text</div>
    <div id="th_4" class="produkte_listeTitleLink">Link</div>
    <div id="th_5" class="produkte_listeTitlePreis">Preis</div>
  </div>
  <div id="tableBody" style="position:relative"></div>
  <div id="loader"></div>
  <div class="clearer"></div>
  <div id="pagination" class="paginationListe"></div>
  <div class="clearer"></div>
</div>


<div id="productEditDialog" style="display:none">
  <input type="HIDDEN" id="productID" value="">
  <div id="div_label_input_titel" class="produktePopuplabelTextInhalt">Titel:</div>   
  <div id="div_input_titel" class="produktePopupAbstandtInput"><input name="product_titel" id="input_titel" class="produktePopupinputAusgabe"></div>
  <div id="div_label_input_teasertext" class="produktePopuplabelTextInhalt" class="produktePopupinputAusgabe">Teasertext:</div>   
  <div id="div_input_teasertext" class="produktePopupAbstandtInput"><textarea name="product_teaser" id="input_teaser" class="produktePopupinputAusgabe"></textarea></div>
  <div id="div_label_input_text" class="produktePopuplabelTextInhalt">Text</div>   
  <div id="div_input_text" class="produktePopupAbstandtInput"><textarea name="product_text" id="input_text" class="produktePopupinputAusgabe"></textarea></div>
  <div id="div_label_input_link" class="produktePopuplabelTextInhalt">Link:</div>   
  <div id="div_input_link" class="produktePopupAbstandtInput"><input name="product_link" id="input_link" class="produktePopupinputAusgabe"></div>
  <div id="div_label_input_preis" class="produktePopuplabelTextInhalt">Preis:</div>   
  <div id="div_input_preis" class="produktePopupAbstandtInput"><input name="product_preis" id="input_preis" class="produktePopupinputAusgabe"></div>
</div>
