<?php

// das View bzw. Form wird "per Hand" gebaut, damit evtl. auch mal
// nicht-Programmierer dort etwas aendern koennen.

?>
<div id="paketListe"  class="produktListe">
  <div id="tableHead" class="paketListeTabelle">
    <div id="th0" class="status">Status</div>
    <div id="th1" class="listeTitle">Titel</div>
    <div id="th2" class="listeProdukte">Produkte</div>
    <div id="th3" class="listeGesamtpreis">Gesamtpreis</div>
  </div>
  <div id="tableBody" style="position:relative"></div>
  <div><br></div>
  <div id="loader"></div>
  <div class="clearer"></div>
  <div id="pagination" class="paginationListe"></div>
  <div class="clearer"></div>
</div>

