<div id="paketNameInput" class="dialog">
  <div>Paketname:</div>
  <div>
    <input type="text" name="paketNameInputField" id="paketNameInputField" value="<?php echo $this->paketName; ?>">
  </div>
</div>
<div id="content" class="content">
  <div id="contentText" class="contentText"><?php echo $this->contentText ?></div>
		<div class="clearer"></div>
		<div id="produktwahl" class="produktwahl">
    <input type="HIDDEN" id="anzahlProdukte" value="<?php echo count ($this->produkte); ?>">
    <?php 
    foreach ($this->produkte as $key => $produkt)
    {
    ?>
  		<div id="produkt<?php echo $key; ?>" class="produkt">
		   	<div id="pfeil<?php echo $key; ?>" class="pfeil">
        <img id="ImageDel_produkt<?php echo $key; ?>" src="/img/pfeil.gif" alt="bild" width="16" height="16" border="0">
      </div>
  				<div id="bild<?php echo $key; ?>" class="kleinBild">
		    		<img src="/img/bild.gif" alt="bild" width="51" height="51" border="0">			
      </div>
   			<div id="textGr<?php echo $key; ?>" class="textTitel">
      <?php echo $produkt ['product_titel']; ?>
      </div>			
  				<div id="textKl<?php echo $key; ?>" class="teaser">
      <?php echo $produkt ['product_teaser']; ?>
      </div>
				  <div id="preis<?php echo $key; ?>" class="preisPaket">
      <input type="HIDDEN" id="paketPreis_produkt<?php echo $key; ?>" value="<?php echo $produkt ['product_preis']; ?>">
      Preis: <?php echo $produkt ['product_preis']; ?>
      </div>
		  </div>
    <?php
    }
    ?>
		</div>

		<div id="paket" class="paket">
  		<div id="paketName" class="paketTitelText">Paket en per Nitesco, arx Persisto, incontinenc</div>
  		<div class="clearer"></div>
    <div id="produkte"></div>
  		<div class="clearer"></div>	
  		<div id="preisProdukt" class="gesamtPaketPreis">Gesamtpreis:&nbsp;<div id="gesamtPreis" style="float:right" class="gesamtPaketPreis">0,00 &euro;</div></div>
  		<input name="senden" type="button" value="speichern" />
		</div>
</div>
<div class="clearer"></div>

