<script language="javascript">

function loadAjaxContent ()
{
  var ajaxURL = "/login/index/index/error/cpwdialog";
  $.ajax (
  {
 		dataType: "json",
 		url: ajaxURL,
    async: false,
    data: {
          },
 		success: function (ajaxData)
 	 					 {
                 fancyModalContent (ajaxData.content);
 						 },
    onComplete : function()
                 {

                 }
    });
}

function showChangePassword ()
{
  $(document).ready(function()
  {
      loadAjaxContent();
      $("#fancyConfirm_ok").click(function()
        {
          if ($("#password1").val () == $("#password2").val ())
          {
            $.ajax (
            {
              dataType: "json",
              url: "/login/index/changepassword",
              async: false,
              data: {
                      newpw: $("#password1").val ()
                    },
              success: function (ajaxData)
                      {
                        if (ajaxData.error < 1)
                        {
                          alert ('Entschuldigung. Das hätte nicht passieren dürfen! Bei der Änderung des Passworts ist ein Fehler aufgetreten. Bitte wenden Sie sich an unsere Technik.');
                          showChangePassword();
                        } else
                          {
                            ret = false;
                            fancyError('Ihr Passwort wurde geändert. Sie können sich jetzt mit Ihrem Benutzernamen und Ihrem neuen Passwort anmelden!')
                            jQuery.fancybox.close();
                          }
                      }
             });
           } else
             {
               alert ("die beiden Passworte stimmen nicht überein. Bitte wiederholen Sie die Eingabe!");
               showChangePassword();
             }
        });
  });
};

showChangePassword();
</script>