<div>
  <div>Aus Sicherheitsgründen bitten wir Sie, jetzt ein neues Passwort festzulegen.</div>
  <div>&nbsp;</div>
  <div class="contentLeft">
    Passwort: <input type="password" id="password1">
    Wiederholung: <input type="password" id="password2">
    <div style="text-align:right;margin-top:10px;">
      <input id="fancyConfirm_ok" style="margin:3px;padding:0px;align:right" type="button" value="OK">
    </div>
  </div>
</div>