<!DOCTYPE html>
<html>
<head>
  <?php
  echo $this->headMeta ();
  echo $this->headTitle ('WEKA Fachmedien Anbieterverzeichnis - Bitte melden Sie sich an');
  echo $this->headScript ()    
  ->prependFile ('/js/jquery/jquery-1.9.1.min.js')              
  ->appendFile ('/js/fancybox/jquery.fancybox.pack.js');  
  echo $this->headLink () 
  ->appendStylesheet ('/js/fancybox/jquery.fancybox.css')       
  ->appendStylesheet ('/css/login.css')
  ->appendStylesheet ('/twitter_bootstrap/css/bootstrap.css');                 
  ?>

  <?php
  
  $useragent = $_SERVER ['HTTP_USER_AGENT'];
  if (preg_match ('|MSIE ([0-9].[0-9]{1,2})|', $useragent, $matched))
  {
    $browser_version = $matched [1];
    $browserVersionArr = explode ('.', $browser_version);
    if ($browserVersionArr [0] <= '8')    
      echo ('<link rel="stylesheet" type="text/css" media="screen" href="/css/IEfix.css">');    
  } 
 
  ?>
</head>
<body>

<input type="hidden" name="module" id="module" value="<?php echo $this->layout ()->_module; ?>">
<input type="hidden" name="controller" id="controller" value="<?php echo $this->layout ()->_controller; ?>">
<input type="hidden" name="action" id="action" value="<?php echo $this->layout ()->_action; ?>">

<div class="hidden"><img src="/images/formField.png"><img src="/images/formFieldFocus.png"><img
src="/images/loginButtonNormal.png"><img src="/images/loginButtonPressed.png"></div>

<div class="clearer"></div>
<div class="backgroundNormal">

  <div class="productLogos">
    <a href="http://www.elektroniknet.de" target="_blank"><img src="/images/elnet.png" class="white"></a>
    <a href="http://www.energie-und-technik.de" target="_blank"><img src="/images/et.png" class="white"></a>
    <a href="http://www.computer-automation.de" target="_blank"><img src="/images/ca.png" class="white"></a>
    <a href="http://www.funkschau.de" target="_blank"><img src="/images/funkschau.png" class="funkschau"></a>   
    <a href="http://www.crn.de" target="_blank"><img src="/images/crn_logo.png" class="white"></a>
  </div>
  <div class="wcosName">Anbieterverzeichnis</div>


  <div class="login">
    <span>Login</span>

    <form id="login" enctype="application/x-www-form-urlencoded" method="post" action="/login/index/go">
      <div class="loginForm">
        <input type="HIDDEN" name="username" id="username">
        <input type="HIDDEN" name="password" id="password">
        <input type="text" value="Benutzername" name="username" onFocus="if(this.value=='Benutzername') this.value=''"
               onBlur="if(this.value=='') this.value='Benutzername'">
        <input type="password" name="password" value="Password" onFocus="if(this.value=='Password') this.value=''" onBlur="if(this.value=='') this.value='Password'">
        <input type="submit" class="loginButton" value="" style="width:50px;">
      </div>           
    </form>
    
    <?php if ($this->error === true) : ?>
        <div class="alert alert-error" style="text-align:center;">         
          <b>Falscher Benutzername oder Passwort</b>           
        </div>
    
    <?php endif; ?>
  </div>
  <!-- login -->
</div>
<div style="text-align:center">WEKA FACHMEDIEN GmbH | Richard-Reitzner-Allee 2 | 85540 Haar | Telefon: +49 (0)89.255
  56-1000 | Fax: +49 (0)89.255 56-1396
</div>
<div style="text-align:center">Gesch&auml;ftsf&uuml;hrer: Kurt Skupin, Werner M&uuml;tzel, Wolfgang Materna |
  Amtsgericht M&uuml;nchen, HRB: 119 806 | Umsatzsteuer-ID-Nummer DE 811 190 616
</div>